null=lm(HappinessScore~1,Happiness)
full=lm(HappinessScore~Economy+Family+Health+Freedom+Trust+Generosity+SuicideRate,Happiness)
step(null,scope=list(upper=full,lower=null))
my_lm=lm(HappinessScore ~ Economy + Freedom + Family + Health + Trust, Happiness)
with(Happiness, cor(data.frame(Economy,Freedom,Family,Health,Trust)))
my_lm2=lm(HappinessScore ~ Economy * Freedom + Family + Health + Trust, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy * Family + Freedom + Health +Trust, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy * Health + Freedom + Family + Trust, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy * Trust + Freedom + Family + Health, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Trust + Freedom * Family + Health, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Trust + Freedom * Health + Family, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Trust * Freedom + Health + Family, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Trust + Freedom + Health * Family, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Freedom + Health + Family * Trust, Happiness)
anova(my_lm,my_lm2)
my_lm2=lm(HappinessScore ~ Economy + Freedom + Health * Trust + Family, Happiness)
anova(my_lm,my_lm2)
model = lm(HappinessScore~Economy * Family + Family * Health + Freedom + Trust, Happiness)
summary(model)
anova(my_lm,model)
model = lm(HappinessScore~Economy * Family + Health + Freedom + Trust, Happiness)
summary(model)
model = lm(HappinessScore~Economy + Family * Health + Freedom + Trust, Happiness)
summary(model)
model = lm(HappinessScore~Economy * Family + Family * Health + Freedom + Trust, Happiness)
summary(model)
model = lm(HappinessScore~Economy * Family * Health + Freedom + Trust, Happiness)
model = lm(HappinessScore~Economy + Family * Health + Freedom + Trust, Happiness)
model = lm(HappinessScore~Economy * Family + Family * Health + Freedom + Trust, Happiness)
anova(my_lm,model)
my_lm2=lm(HappinessScore ~ Economy * Family + Freedom + Health + Trust, Happiness)
anova(my_lm2, model)
my_lm2=lm(HappinessScore ~ Economy + Trust + Freedom + Health * Family, Happiness)
anova(my_lm2,model)
model = lm(HappinessScore~Economy * Family * Health + Freedom + Trust, Happiness)
anova(my_lm2,model)
summary(model)
> with(Happiness,plot(SuicideRate,HappinessScore))
> with(Happiness,histogram(Economy,xlim=c(0,2)))
> with(Happiness,histogram(Family,xlim=c(0,2)))
> with(Happiness,histogram(Health,xlim=c(0,2)))
> with(Happiness,histogram(Freedom,xlim=c(0,2)))
> with(Happiness,histogram(Trust,xlim=c(0,2)))
> with(Happiness,histogram(Generosity,xlim=c(0,2)))